set_lib_cell_purpose -include cts {*/AND2X2_HVT}
set_lib_cell_purpose -include cts {*/AND2X1_HVT}
set_lib_cell_purpose -include cts {*/AND2X4_HVT}
set_lib_cell_purpose -include cts {*/AO22X1_HVT}
set_lib_cell_purpose -include cts {*/AO22X2_HVT}
set_lib_cell_purpose -include cts {*/AOI22X1_HVT}
set_lib_cell_purpose -include cts {*/AOI22X2_HVT}
set_lib_cell_purpose -include cts {*/CGLNPRX2_HVT}
set_lib_cell_purpose -include cts {*/CGLNPRX8_HVT}
set_lib_cell_purpose -include cts {*/CGLPPRX2_HVT}
set_lib_cell_purpose -include cts {*/CGLPPRX8_HVT}
set_lib_cell_purpose -include cts {*/MUX21X1_HVT}
set_lib_cell_purpose -include cts {*/MUX21X2_HVT}
set_lib_cell_purpose -include cts {*/AND2X2_RVT}
set_lib_cell_purpose -include cts {*/AND2X1_RVT}
set_lib_cell_purpose -include cts {*/AND2X4_RVT}
set_lib_cell_purpose -include cts {*/AO22X1_RVT}
set_lib_cell_purpose -include cts {*/AO22X2_RVT}
set_lib_cell_purpose -include cts {*/AOI22X1_RVT}
set_lib_cell_purpose -include cts {*/AOI22X2_RVT}
set_lib_cell_purpose -include cts {*/CGLNPRX2_RVT}
set_lib_cell_purpose -include cts {*/CGLNPRX8_RVT}
set_lib_cell_purpose -include cts {*/CGLPPRX2_RVT}
set_lib_cell_purpose -include cts {*/CGLPPRX8_RVT}
set_lib_cell_purpose -include cts {*/MUX21X1_RVT}
set_lib_cell_purpose -include cts {*/MUX21X2_RVT}
set_lib_cell_purpose -include cts {*/AND2X2_LVT}
set_lib_cell_purpose -include cts {*/AND2X1_LVT}
set_lib_cell_purpose -include cts {*/AND2X4_LVT}
set_lib_cell_purpose -include cts {*/AO22X1_LVT}
set_lib_cell_purpose -include cts {*/AO22X2_LVT}
set_lib_cell_purpose -include cts {*/AOI22X1_LVT}
set_lib_cell_purpose -include cts {*/AOI22X2_LVT}
set_lib_cell_purpose -include cts {*/CGLNPRX2_LVT}
set_lib_cell_purpose -include cts {*/CGLNPRX8_LVT}
set_lib_cell_purpose -include cts {*/CGLPPRX2_LVT}
set_lib_cell_purpose -include cts {*/CGLPPRX8_LVT}
set_lib_cell_purpose -include cts {*/MUX21X1_LVT}
set_lib_cell_purpose -include cts {*/MUX21X2_LVT}
set_lib_cell_purpose -include cts {*/LSUPX1_HVT}
set_lib_cell_purpose -include cts {*/LSUPX2_HVT}
set_lib_cell_purpose -include cts {*/LSUPX4_HVT}
set_lib_cell_purpose -include cts {*/LSUPX8_HVT}
set_lib_cell_purpose -include cts {*/LSUPX1_RVT}
set_lib_cell_purpose -include cts {*/LSUPX2_RVT}
set_lib_cell_purpose -include cts {*/LSUPX4_RVT}
set_lib_cell_purpose -include cts {*/LSUPX8_RVT}
set_lib_cell_purpose -include cts {*/LSUPX1_LVT}
set_lib_cell_purpose -include cts {*/LSUPX2_LVT}
set_lib_cell_purpose -include cts {*/LSUPX4_LVT}
set_lib_cell_purpose -include cts {*/LSUPX8_LVT}
